name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Runs at midnight every day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Create dist directory
        run: mkdir -p dist

      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output: dist/github-snake.svg

      - name: Commit and push
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "github-actions[bot]"
          author_email: "github-actions[bot]@users.noreply.github.com"
          message: "Generate snake animation"
          add: "dist/github-snake.svg"
